// AUTO-GENERATED by gen.cjs — do not edit by hand. `node gen.cjs` to regenerate.
export const LEVELS = [
 {
  "name": "The Threshold",
  "taunt": "Just walk to the light. Easy.",
  "grid": [
   "#########",
   "#So^o^o^#",
   "#....^^o#",
   "#^o^..o^D",
   "#o^o^.^o#",
   "#^o^o.o^#",
   "#o^o^..o#",
   "#^o^o^.G#",
   "#########"
  ],
  "pathLen": 13,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 7,
   "c": 7
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "Decorative Doors",
  "taunt": "The doors are a lie. Ignore them.",
  "grid": [
   "#########",
   "#So^o^o^#",
   "#...^o^o#",
   "#^o.o^o^#",
   "#o^.^o^o#",
   "#^o..^o^#",
   "#o^^...o#",
   "#^o^o^..#",
   "#o^o^o^.#",
   "#^o^o^oG#",
   "######D##"
  ],
  "pathLen": 15,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 9,
   "c": 7
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "The Floor Lies",
  "taunt": "It looked solid. It wasn't.",
  "grid": [
   "####D######",
   "#S..o^o^o^#",
   "#o^.^^^o^o#",
   "#^o....^o^#",
   "#o^o^o.o^o#",
   "#^o^o^.^o^#",
   "#o^o^o...o#",
   "#^o^o^o^.^#",
   "#o^o^o^o.o#",
   "#^o^o^o^.G#",
   "######D####"
  ],
  "pathLen": 17,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 9,
   "c": 9
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "Pillars of Salt",
  "taunt": "Don't look back. Don't step wrong.",
  "grid": [
   "###########",
   "#So^o^o^P^#",
   "#...^o^o^o#",
   "#^o.o^o^o^D",
   "#o^.^o^o^oD",
   "#^o..^o^o^#",
   "#o^o.o^o^o#",
   "#^o^..P^o^#",
   "#o^o^.^o^o#",
   "#^o^o...o^#",
   "#o^o^o^...#",
   "#Po^o^o^^G#",
   "###########"
  ],
  "pathLen": 19,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 11,
   "c": 9
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "Hot Floor",
  "taunt": "Mind the puddles. They bite.",
  "grid": [
   "###########",
   "#SoPP^o^o~#",
   "#..o^o^P~~D",
   "#^.^^^o^o^#",
   "#o...^^o^o#",
   "#^oP.^o^o^#",
   "#o^o.o^o^o#",
   "#^o^.^o^o^#",
   "#o^o.o^o^o#",
   "#^o^...^o^#",
   "#o^o^o.o^oD",
   "#^o^o^...G#",
   "######D####"
  ],
  "pathLen": 19,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 11,
   "c": 9
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "Launch Window",
  "taunt": "That jump was illegal.",
  "grid": [
   "#############",
   "#S...^o^o^o^#",
   "#o^J...o^o^oD",
   "#^o^o^..o^o^D",
   "#o^P^P^.....#",
   "#^o^o^oPo^o.#",
   "#o^o^o^o^o^.#",
   "#^o^o^o^o^^.D",
   "#o^o^o^o^o^.#",
   "#^o^o^o^o^o.#",
   "#o~~^o^o^o^.#",
   "#^~^o^o^oPoG#",
   "#############"
  ],
  "pathLen": 21,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 11,
   "c": 11
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "Overhead",
  "taunt": "Heads up. Too late.",
  "grid": [
   "#############",
   "#S.^o^o^o^o^#",
   "#o..^o^o^o^o#",
   "#^o.P^o^^^oPD",
   "#oJ.......^o#",
   "#^o^o^o^C...#",
   "#o^o^o^o^o^.#",
   "#^P^o^o^o^o.#",
   "#o^oPo^o^o^.#",
   "#^o^o^o^o^o.#",
   "#o^o~o^P^o^.#",
   "#^o~~^o^o^o.D",
   "#o^o~o^o^o^.#",
   "#^o^o^o^o^oG#",
   "##D#####D####"
  ],
  "pathLen": 23,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 13,
   "c": 11
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "The Long Con",
  "taunt": "Halfway is nowhere.",
  "grid": [
   "#############",
   "#S.^o^o^o^o^#",
   "#o...o^oPo^o#",
   "#^P^.^o^o^o^#",
   "#o^o..^P^o^o#",
   "#^o^o.o^o^o^#",
   "#o^o^.^o^o^oD",
   "#^o^o.o^o^o^#",
   "#o^o^.Co^o^o#",
   "#^o^o.o^o^o^#",
   "#o^o^....P^o#",
   "D^o^o^o^.^o^#",
   "#o^~^oPo.oJ^#",
   "#^~~~^o^...G#",
   "#######D##D##"
  ],
  "pathLen": 23,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 13,
   "c": 11
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "No Tells",
  "taunt": "You know the drill by now. You don't.",
  "grid": [
   "##D###D########",
   "#So^o^o^o^o^o^#",
   "#......o^o^o^o#",
   "#Jo^o^.^o^o^o~#",
   "#o^o^o..^o^o~~#",
   "D^o^o^P.o^o^o~D",
   "#o^o^o^.^o^o^o#",
   "#^o^o^o...oCo^#",
   "#o^o^oPo^...^o#",
   "#^o^o^o^o^o..^#",
   "#o^o^o^oPP^o..#",
   "#^o^o^o^o^oPo.#",
   "#o^o^o^o^o^oP.#",
   "#^o^o^o^o^o^oG#",
   "###D###########"
  ],
  "pathLen": 25,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 13,
   "c": 13
  },
  "risingLava": false,
  "riseTime": 0
 },
 {
  "name": "The Floor Is Lava",
  "taunt": "Literally. Run.",
  "grid": [
   "###D####D#D#D##",
   "#S..o^o^o^oPo^#",
   "#o^.Jo^o^o^o^o#",
   "#^o..^o^o^o^o^#",
   "#o^o..^o^o^o^o#",
   "#^o^^..^o^o^o^#",
   "#o^oPo.o^o^o^o#",
   "#^o^~^..o^o^o^#",
   "#o^~~~^.^o^o^o#",
   "#^o^~^P.o^o^o^#",
   "#o^oPo^..o^o^o#",
   "#^o^o^oC.....^#",
   "#o^o^o^oPo^o.^#",
   "#^o^o^o^o^P^.^#",
   "#o^o^o^o^o^o.^#",
   "#^o^o^o^o^o^.G#",
   "##D############"
  ],
  "pathLen": 27,
  "start": {
   "r": 1,
   "c": 1
  },
  "goal": {
   "r": 15,
   "c": 13
  },
  "risingLava": true,
  "riseTime": 32
 }
];
export default LEVELS;
